### ISSUE TITLE
As a player, I would like to parry a bullet

### ISSUE THREAD

**Issue by leohlim** [leohlim/SamuraiJam2024#7]
When a monster shoots at me, I can strike the bullet at the right time to destroy the bullet and the monster.

Requirements:
- [x] Set up a separate scene with one projectile monster and the player
- [x] When the player strikes at the monster's bullet, destroy the bullet and the monster

**Comment by Zach-Kolman** [comment]
Bullet doesn't get destroyed, but reverses speed and changes directions back to the shooter.

**Comment by Zach-Kolman** [comment]
Post-hitstop bullet movement is not behaving correctly. Will reevaluate tomorrow.
