### ISSUE TITLE
As a designer, I want to juice the parry mechanic to feel powerful

### ISSUE THREAD

**Issue by leohlim** [leohlim/SamuraiJam2024#8]
When the player parries the bullet, they should feel like a god

Requirements:

- [x] Sound effects for when you slash the bullet (like a crunch or a snap?) and when the monster dies (explosion)
- [x] Add a hitstop at the moment of impact. Slow down the game time and then resume after an adjustable time.

Stretch:
- [x] Apply a shake to the bullet when it gets hit
- [x] Apply the sparks particle when hit

**Comment by Zach-Kolman** [comment]
All requirements and stretch completed.
